# Generated by Django 2.2.17 on 2021-01-21 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210121_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='adctivation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 6, 9, 19, 450425, tzinfo=utc)),
        ),
    ]
