# Generated by Django 2.2.17 on 2021-01-21 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210121_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='adctivation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 6, 24, 16, 110712, tzinfo=utc)),
        ),
    ]
